name: 'Build Corne-ish Zen v2 Custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      shield: '["default"]'
      alphas: '["Colemak"]'
      nav: '["vi"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["default"]'
      branches: '["default"]'
      modules: '["default"]'
      extra: '["default"]'
      tap: '["default"]'
      clipboard: '["mac"]'
